### ISSUE TITLE
Cannot deploy to Genymotion 

### ISSUE THREAD

**Issue by jamesnyika** [alwx/luno-react-native#11]
I think there is a failed dependency with material dialogs..how does one update the version of material dialogs ? it is currently at 0.8.5.8 ... up from .0 which you originally had... 

thanks

 => react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > A problem occurred configuring project ':react-native-dialogs'.
  > Could not resolve all dependencies for configuration ':react-native-dialogs:_debugCompile'.
  > Could not find com.github.afollestad.material-dialogs:core:0.8.5.0.
  >     Searched in the following locations:
  >         file:/Users/james.nyika/.m2/repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
  >         file:/Users/james.nyika/.m2/repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
  >         https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
  >         https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
  >         https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
  >         https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
  >         file:/Users/james.nyika/personal/android-sdk-macosx/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
  >         file:/Users/james.nyika/personal/android-sdk-macosx/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
  >     Required by:
  >         luno:react-native-dialogs:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.098 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by mcin-armintaheri-archive** [comment]
I am having the same issue with stock emulator.
It seems like a dependency issue with react-native-dialogs. 

You can edit
`luno-react-native/node-modules/react-native-dialogs/android/build.gradle` 
and you can modify the dependencies to

```
dependencies {
    compile 'com.android.support:appcompat-v7:23.+'
    compile 'com.facebook.react:react-native:0.14.+'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile('com.github.afollestad.material-dialogs:core:0.8.5.8@aar') {
        transitive = true
    }
}
```

**Comment by akirill0v** [comment]
@jamesnyika 
... and try this before deploy:

`re-natal use-android-device genymotion`

**Comment by pkvov** [comment]
no luck with the same problem
