### ISSUE TITLE
Unfortunately luno has stopped.

### ISSUE THREAD

**Issue by mcin-armintaheri-archive** [alwx/luno-react-native#12]
I've followed the solution I gave on issue #11 and have been able to get the luno apk to install on the stock emulator. The problem is when launching the application, it instantly crashes. I can't seem to find any sequence of building and running commands to get it to work.

![crop from 2016-04-10 02 45 56](https://cloud.githubusercontent.com/assets/6931970/14408549/1c9fd4a8-fec7-11e5-8871-9e8ed839f22f.png)

**Comment by alwx** [comment]
Sorry for the delay with the answer.
I am going to fix it today or tomorrow. Most probably an update of react-native and re-natal will help, but if not, I will look for possible solutions.

Thanks for reporting!
