### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by peterromfeldhk** [alwx/luno-react-native#17]
Or better said, i cant get `react-native run-android` to work, not sure what the issue is - maybe i missed something

I'm getting:

![screenshot_20160717-213837](https://cloud.githubusercontent.com/assets/5515707/16900959/78a79d4c-4c67-11e6-88a2-3b81255a9881.png)

**Comment by alwx** [comment]
Have never seen an error like the one on the screenshot. Are you sure that you haven't missed something? I've seen that you also created a fork, did you find a way to fix that?
